language: rust

rust:
  - nightly
  - beta
  - stable

  os:
  - linux
  - windows
  - osx

script:
  - cargo build && cargo test
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then cargo bench; fi
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then cargo build --features "use_simd" && cargo test --features "use_simd" && cargo bench --features "use_simd"; fi
